apiVersion: v1
kind: Service
metadata:
  name: feelory-backend-service
  namespace: feelory
spec:
  selector:
    app: feelory-backend-deploy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP